services:

  delivery:
    image: node:20.10
    container_name: delivery
    working_dir: /delivery
    volumes:
      - ./:/delivery
    ports: 
      - ${DELIVERY_PORTS}
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${MONGO_PORTS}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: delivery

